# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python lint and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Set up uv
      run: |
        curl -LsSf https://astral.sh/uv/0.3.2/install.sh | sh
    - name: Install dependencies with uv
      run: |
        uv pip install flake8
        uv pip install -r requirements.txt
        uv pip install -r test-requirements.txt
      env:
        UV_SYSTEM_PYTHON: 1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
      env:
        OPENAI_API_KEY: sk-fake-openai-key
        GROQ_API_KEY: gsk_fake_groq_key
